# Generated by Django 4.1.2 on 2022-10-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_cart_order_cartproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartproduct',
            old_name='quntity',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='payment_complete',
            new_name='payment',
        ),
        migrations.AlterField(
            model_name='cart',
            name='complit',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order canceled', 'Order canceled'), ('Order Received', 'Order Received'), ('Order Completed', 'Order Completed'), ('On The Way', 'On The Way'), ('Order Processing', 'Order Processing')], default='Order Received', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(upload_to='profile/'),
        ),
    ]
